### ISSUE TITLE
[Refactor] 2주차 과제 리팩토링

### ISSUE THREAD

**Issue by HELLOHIDI** [DO-SOPT-iOS-Part/RyuHeeJae_assignment#11]
## 🛠 Issue
- 2주차 과제 리팩토링

## 📋 To-do
- [ ] DetailViewController pageViewController로 변경
- [ ] Coordinator 패턴 적용하기
- [ ] tuist에 맞도록 의존성 관리하기
