### ISSUE TITLE
[Assignment] 4주차 과제 

### ISSUE THREAD

**Issue by HELLOHIDI** [DO-SOPT-iOS-Part/RyuHeeJae_assignment#15]
## 🛠 Issue
- 4주차 과제

## 📋 To-do
- [x] Data 모듈에 Repository 패턴 구현
- [x] Data 모듈에 domain 모델 형식으로 변환하는 Transform 구현
- [x] Domain 모듈에 RepoositoryInterface 구현
- [x] Network 모듈 URLSession 활용한 Service 구현
- [x] Network 통신 async await 사용해서 구현
- [x] Domain UseCase에서 Feature로 데이터 뿌려주기 구현
