### ISSUE TITLE
[Refactor] Coordinator Pattern + Factory Pattern 적용하기

### ISSUE THREAD

**Issue by HELLOHIDI** [DO-SOPT-iOS-Part/RyuHeeJae_assignment#20]
## 🛠 Issue
- UIKit에서의 코디네이터 패턴과 팩토리 패턴을 적용해보기

## 📋 To-do
- [ ] ViewControllerable 파일 만들기
- [ ] BaseFeatureDependency에 Coordinator 패턴 만들기
- [ ] BaseFeatureDependency에 Router 만들기
- [ ] RootFeature에 AppCoordinator 만들기
- [ ] 각 Feature에 맞는 Coordinator 패턴 적용하기
