### ISSUE TITLE
[Assingment] 2주차 기본 & 심화 과제

### ISSUE THREAD

**Issue by HELLOHIDI** [DO-SOPT-iOS-Part/RyuHeeJae_assignment#9]
## 🛠 Issue
- 2주차 기본과제

## 📋 To-do
- [x] Main Feature UseCase 만들기
- [x] Main Feature ViewModel 만들기
- [x] Main Feature View  만들기
- [x] Detail Feature UseCase 만들기
- [x] Detail Feature ViewModel 만들기
- [x] Detail Feature View  만들기
